const router = require('express').Router();
const { checkToken } = require('../../auth/token_validation');
const { createUser,login,getUsers,getUsersById,updateUser,deleteUser } = require('./user.controller');
router.post('/',checkToken,createUser);
router.get('/',checkToken,getUsers);
router.get('/:id',checkToken,getUsersById);
router.patch('/:id',checkToken,updateUser);
router.delete('/:id',checkToken,deleteUser);
router.post('/login',login);
module.exports = router;